### ISSUE TITLE
PremiumAccountRequired issue

### ISSUE THREAD

**Issue by FelixHutnyk** [agneevX/librespot-java-docker#5]
When trying to stream to the server it throws the following error.
`xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: PremiumAccountRequired
	at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:450) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.core.Session.authenticate(Session.java:339) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.core.Session.access$600(Session.java:77) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1029) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer.handleAddUser(ZeroconfServer.java:367) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer.access$200(ZeroconfServer.java:56) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:499) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:574) ~[librespot:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:482) ~[librespot:1.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

This has been fixed in version 1.6.3 of librespot-java. 

The docker image needs to be updated.

**Comment by agneevX** [comment]
Can you check to see whether it solves your issue or not?

**Comment by rinzeb** [comment]
For me it solved the issue, thanks!

**Comment by FelixHutnyk** [comment]
Amazing! Thank you for the speedy fix.
